# To use the ingest scripts, you must have synced the SharePoint root directory with your OneDrive account
#    1) go to SharePoint root directory (can get this from any file in MS Teams > right-click option)
#    2) three dots "..." in Sharepoint > sync
#
# Then, you must set up your profile and paths in local_paths.yaml
#    1) local_paths.example contains the example script
#    2) Choose your profile name (currently "sarka")
#    3) From your synced SharePoint directory location:
#        - get the address. Should be identical to example but with unique id instead of REPLACE_ME
#        - add in correct address. Note: replace Windows generated "\" with "/" if necessary
#    4) You should not need to edit paths (unless the SharePoint folder structure has been altered).
#
#    If paths has been changed see README.md in the inventory_db folder for subfolder structure
#
# Finally, save this as local_paths.yaml.
#   - This is for local use only - do not push to Git.
#   - Recommend adding to tests/gitignore if not already in place.

# This points to the root SharePoint directory
profiles:
  sarka:
    sharepoint_root: "C:/Users/REPLACE_ME/University of Edinburgh/Carbon accounting of fire events - Fire-Emissions-Databases"

# These point to the current databases.
# They contain: 
#     - root (what the database root directory is called)
#     - rel_db (the actual filepath/filename of the database)
#     - raw_types (the permissable ingest data types)
# Add or delete as appropriate
db_roots:
  inventory_db:  # Where the item and survey data is currently stored
    root: "inventory_db"
    rel_db: "database/pooled_inventory.sqlite"
    raw_types: ["vocab", "survey"]

  fire_db:  # Where the fire incident (FRIS) data will eventually be stored
    root: "fire_db"
    rel_db: "database/fire_incidents.sqlite"
    raw_types: ["fris"]

  test_db: # For development/dubugging - should mirrored db under test
    root: "test_db"
    rel_db: "database/pooled_inventory.sqlite"
    raw_types: ["vocab", "survey", "assumed"]

# These specify the exact location of the ingest source files
# These must be included in the raw_types list or they will not be ingested
# Add or delete as appropriate
paths:
  vocab:  
    rel_raw: "config/vocab"  # the item mappings
  survey:
    rel_raw: "raw/surveys"   # the raw jisc output file
  assumed:
    rel_raw: "config/vocab"  # the assumed items list
  fris:
    rel_raw: "raw/fris"      # the FRIS data (currently not implemented)
  lca: 
    rel_raw: "raw/lca"       # the LCA data (currently not implemented)

  